global proc module_installer()
{
	string $filePath = `whatIs module_installer`;
	string $installer = "tbtoolsInstaller.py";

	$filePath = `substitute "Mel procedure found in: " $filePath ""`;
	$filePath = `substitute "drag_me_into_maya.mel" $filePath  ""`;

    string $exec_cmd =("exec(open(\"" + $filePath + $installer + "\").read())");

    print ($exec_cmd + "\n");
    python($exec_cmd);
	
}

module_installer;