global proc module_installer()
{
	string $filePath = `whatIs module_installer`;
	string $installer = "tbtoolsInstaller.py";

	$filePath = `substitute "Mel procedure found in: " $filePath ""`;
	$filePath = `substitute "drag_me_into_maya.mel" $filePath  ""`;

	string $sys_cmd = ("sys.path.append(\"" + $filePath + "\")");

	python($sys_cmd);
	python("import tbtoolsInstaller as installer");
	python("installer.install()");
}

module_installer;